### ISSUE TITLE
Use MonadFail to make monad-supply fit for ghc >= 8.6

### ISSUE THREAD

**Issue by EsGeh** [ghulette/monad-supply#9]
monad-supply currently fails to compile with ghc 8.6.

```
-- While building custom Setup.hs for package monad-supply-0.7 using:
      <...>/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.1 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1 build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
    Logs have been written to: <...>/.stack-work/logs/monad-supply-0.7.log

    Configuring monad-supply-0.7...
    Preprocessing library for monad-supply-0.7..
    Building library for monad-supply-0.7..
    [1 of 1] Compiling Control.Monad.Supply ( src/Control/Monad/Supply.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/Control/Monad/Supply.o )
    
    /tmp/stack-b9ea22a81712ce47/monad-supply-0.7/src/Control/Monad/Supply.hs:43:25: error:
        • Could not deduce (Control.Monad.Fail.MonadFail m)
            arising from a do statement
            with the failable pattern ‘(x : xs)’
          from the context: Monad m
            bound by the instance declaration
            at src/Control/Monad/Supply.hs:42:10-47
          Possible fix:
            add (Control.Monad.Fail.MonadFail m) to the context of
              the instance declaration
        • In a stmt of a 'do' block: (x : xs) <- get
          In the second argument of ‘($)’, namely
            ‘do (x : xs) <- get
                put xs
                return x’
          In the expression:
            SupplyT
              $ do (x : xs) <- get
                   put xs
                   return x
       |
    43 |   supply = SupplyT $ do (x:xs) <- get
       |                         ^^^^^^^^^^^^^
    
compilation failed!
```

**Comment by laserpants** [comment]
@ghulette Any thoughts on my PR?

**Comment by laserpants** [comment]
Thanks for merging. If this can be considered resolved, I suggest closing this issue.
